version: '3'

services:
  sqldata:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      MSSQL_SA_PASSWORD: 1q2w3e4r@#
      ACCEPT_EULA: Y
    ports:
      - '1433:1433'

#default user = sa
